services:
  database:
    image: postgres:16-alpine
    container_name: inventory-postgres
    environment:
      POSTGRES_DB: inventorydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      kafka:
        condition: service_started

    ports:
      - "5432:5432"
    volumes:
      - inventory-postgres-data:/var/lib/postgresql/data

    secrets:
      - db_password
volumes:
  inventory-postgres-data:

secrets:
  db_password:
    file: ./db_password.txt

